# Generated by Django 4.0.3 on 2022-04-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_remove_place_card_img_remove_place_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='address_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
